name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v2
    - name: NPM or Yarn install with caching
      uses: bahmutov/npm-install@v1.1.0
    - name: Build
    - run: yarn build
