name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: PNPM install
        uses: pnpm/action-pnpm-install@v1
        with:
          pnpm-args: "install"
          pnpm-registry: "https://registry.npmjs.org"
          pnpm-store-dir: "./.store"
      - name: Build
        run: yarn build
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@master
        env:
          EMAIL: alanrsoars@gmail.com
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BUILD_DIR: build/